---
  Name: userconfig
---
SilverStripe\Security\Group:
  extensions:
    - ilateral\SilverStripe\Users\Extensions\GroupExtension
SilverStripe\Security\Member:
  extensions:
    - ilateral\SilverStripe\Users\Extensions\MemberExtension
SilverStripe\Control\Controller:
  extensions:
    - ilateral\SilverStripe\Users\Extensions\ControllerExtension