---
Name: usersconfig
---
SilverStripe\Security\Group:
  extensions:
    - DFT\SilverStripe\Users\Extensions\GroupExtension
SilverStripe\Security\Member:
  required_fields:
    - "FirstName"
    - "Surname"
    - "Email"
  extensions:
    - DFT\SilverStripe\Users\Extensions\MemberExtension
SilverStripe\Control\Controller:
  extensions:
    - DFT\SilverStripe\Users\Extensions\ControllerExtension