---
Name: usersroutes
After: framework/routes#rootroutes
---
SilverStripe\Control\Director:
  rules:
    'users/register//$Action/$ID/$OtherID': 'DFT\SilverStripe\Users\Control\RegisterController'
    'users/account//$Action/$ID': 'DFT\SilverStripe\Users\Control\AccountController'