---
Name: userroutes
After: framework/routes#rootroutes
---
Director:
  rules:
    'users/register//$Action/$ID': 'Users_Register_Controller'
    'users/account//$Action/$ID': 'Users_Account_Controller'
